<?php

/**
 * @file
 * Functions to support theming in the <%= themeMachineName %> theme.
 */
use Drupal\Core\Template\RenderWrapper;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_preprocess_HOOK() for block.html.twig.
 */
function <%= themeMachineName %>_preprocess_block(&$variables) {
  // Add classes to blocks.
  if (!empty($variables['attributes']['id'])) {
    $variables['attributes']['class'][] = preg_replace('/^block-/', '', $variables['attributes']['id']);
  }
}
